### ISSUE TITLE
Use case for timetrace get?

### ISSUE THREAD

**Issue by jwnpoh** [dominikbraun/timetrace#154]
Hi there, 

Wondering what's the intended use case for `timetrace get`? The logic of this command seems circular to me: the output displays the key, but I would already have known the key in order to use the command in the first place.

Thanks!

**Comment by dominikbraun** [comment]
Hi,

you're right that there currently is little value in running `timetrace get record` compared to `timetrace list records`. This is because at the moment, all data stored for a record is already displayed in the table printed by `list records`.

However, this could change in the future: There might be data added to a single record, e.g. tags or descriptions (see #115), which will not be displayed in the `list records` table but only in the `get record` output.

**Comment by jwnpoh** [comment]
Yes, that makes sense now. Thanks!
